import { z } from 'zod';

export const childCreateSchema = z.object({
  name: z.string().trim().min(1),
  lastName: z.string().trim().min(1),
  documentType: z.string().trim().min(1),
  documentNumber: z.string().trim().min(1),
  documentFrontPhoto: z.string().trim().min(1),
  documentBackPhoto: z.string().trim().min(1),
  birthDate: z.string().trim().min(1),
  address: z.string().trim().min(1),
  gender: z.enum(['FEMALE', 'MALE', 'NON_BINARY', 'UNDISCLOSED', 'OTHER']),
  nationality: z.string().trim().min(1),
  maritalStatus: z.string().trim().min(1),
  allergies: z.string().trim().min(1),
  regularMedication: z.string().trim().min(1),
  relevantDiseases: z.string().trim().min(1),
  previousInjuries: z.string().trim().min(1),
  physicalRestrictions: z.string().trim().min(1),
  bloodGroup: z.string().trim().min(1),
  primaryDoctor: z.string().trim().min(1),
  doctorPhone: z.string().trim().min(1),
  doctorCertificate: z.string().optional(),
  observations: z.string().trim().min(1),
});
