'use client';
import { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { ACTIVITY_CART_STORAGE_KEY, ActivityCartItem } from '@/lib/cart';
export default function ActivitiesCartPage() { const [items,setItems]=useState<ActivityCartItem[]>([]); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null);
useEffect(()=>{const raw=window.localStorage.getItem(ACTIVITY_CART_STORAGE_KEY); if(!raw) return; try{setItems(JSON.parse(raw) as ActivityCartItem[]);}catch{window.localStorage.removeItem(ACTIVITY_CART_STORAGE_KEY);}},[]);
const total=useMemo(()=>items.reduce((a,i)=>a+Number(i.price||0),0),[items]);
const persist=(next:ActivityCartItem[])=>{setItems(next); window.localStorage.setItem(ACTIVITY_CART_STORAGE_KEY, JSON.stringify(next));};
const handleCheckout=async()=>{setSubmitting(true);setError(null); try{const response=await fetch('/api/activities/cart/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})}); const data=await response.json(); if(!response.ok){setError(data?.error||'No se pudo iniciar el pago.');return;} if(data?.redirectUrl){window.localStorage.removeItem(ACTIVITY_CART_STORAGE_KEY); window.location.href=data.redirectUrl;}}catch{setError('No se pudo iniciar el pago.');}finally{setSubmitting(false);}};
return <main className="mx-auto max-w-3xl px-4 py-10 space-y-6"><h1 className="text-2xl font-semibold">Carrito de actividades</h1>{items.length===0?<p className="text-muted-foreground">No hay actividades en el carrito.</p>:<><ul className="space-y-3">{items.map((item,index)=><li key={`${item.activityId}-${item.target}-${index}`} className="border rounded-md p-4 flex items-center justify-between gap-4"><div><p className="font-medium">{item.activityName}</p><p className="text-sm text-muted-foreground">Inscripción: {item.targetLabel}</p></div><div className="flex items-center gap-3"><span className="font-semibold">${Number(item.price).toLocaleString('es-AR')}</span><Button variant="outline" onClick={()=>persist(items.filter((_,i)=>i!==index))}>Quitar</Button></div></li>)}</ul><div className="border-t pt-4 flex items-center justify-between"><p className="text-lg font-semibold">Total: ${total.toLocaleString('es-AR')}</p><Button onClick={handleCheckout} disabled={submitting}>{submitting?'Procesando...':'Pagar carrito'}</Button></div>{error&&<p className="text-sm text-red-600">{error}</p>}</>}</main>; }
